name: Devops Pipeline

on:
    push:
        branches:
                -main


jobs:
    code:
        runs-on: ubuntu-latest
        steps:
              run: echo "Code Successfully run"
    #build:
    #test:
    #deploy:
